### ISSUE TITLE
Other players are ~20km under current altitude when flying when automatic time is not set in Windows settings

### ISSUE THREAD

**Issue by CorvetteCole** [LunaMultiplayer/LunaMultiplayer#132] opened 2018-05-02 22:39 UTC
Files:
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1969092/KSP.log)
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1969093/output_log.txt)
[Universe.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1969098/Universe.zip)
[Config.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1969099/Config.zip)
[Server Logs](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1969097/logs.zip)

------------------------------------------------------------------------------

OS: 
Windows 10 Pro (Fall 2017 Update)

------------------------------------------------------------------------------

KSPVersion: 
1.4.3

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.7.41

------------------------------------------------------------------------------

MODS (add link to download them): 
no mods, full stock

------------------------------------------------------------------------------

Expected behaviour: 
Players are able to see other players flying around at their proper locations

------------------------------------------------------------------------------

Current behaviour: 
When not on the ground, other players in the session appear roughly 20km below their actual altitude. When on the ground, such as at the KSC runway, the other player's position is relayed perfectly. The moment they are no longer touching the ground they suddenly go ~20km underground

------------------------------------------------------------------------------

Steps to reproduce: 
Download LMP 0.7.41, install the mod from scratch on a completely stock game. Start the server from scratch, completely stock. Have one player be on the runway or flying near KSC while another takes off. Once one player goes in the air they will appear ~20km under their actual altitude.

Additional info:
We tried SO many steps to troubleshoot this, I will say all of them here. Originally this problem existed on a server I created to replace the DarkMultiPlayer server I was running. We had a few mods and a universe. I saved the universe in ksp and exported that for Luna. Next I used that universe with a modcontrol file generated by luna. This worked perfectly until we decided to fly at the same time to see how much smoother luna was. Whenever either my friend or I took off from the ground we would immediately appear ~20km underground. When spectating my friend through the tracking station it still showed hiim far underground with his ship eventually heating up and exploding (on my screen only). 

Steps we took to attempt to fix this:
- Uninstall all mods
- Start with fresh universe
- Reinstall LunaMultiplayer from scratch on both clients and the server
- Connect to the server through the Master Server list instead of directly through the open port on my router
- Cry about why nobody loves me
- Turn interpolation off
- Time warp ahead and have friend sync to my subspace
- Turn safety bubble off
- Change time warp control to None or Master

None of these steps worked (I should mention, they stack. Meaning at the end all steps were active). I have no idea what is wrong but I have programming experience so I may try and poke around and debug a bit (not for awhile though, finals). I'm happy to provide any more info or try things as needed, don't hesitate to ask.

**Comment by gavazquez** [comment] 2018-05-03 07:20
I think that this bug is related to this one:
https://github.com/LunaMultiplayer/LunaMultiplayer/issues/129

Can you try it with latest nightly version?

**Comment by CorvetteCole** [comment] 2018-05-03 15:06
@gavazquez I will try the latest nightly when I have time tonight. I'll reply with my update.

**Comment by CorvetteCole** [comment] 2018-05-03 22:00
@gavazquez So I've tested this with two clients running on my PC and it seems to be working as expected. I will need to wait and get my friend on to test this between two seperate PCs. I did however discover another bug which I'm not sure why it exists. Basically if two people flying the same ship (and name, eg a stock ship) are within 2km of each other one of them will experience rapid unplanned disassembly and end up spectating the other player

**Comment by gavazquez** [comment] 2018-05-03 22:27
Hi @CorvetteCole regarding that second bug you've found, would it be possible to make a video or some reproduction steps? Couldn't reproduce it on my side with latest release

**Comment by CorvetteCole** [comment] 2018-05-03 22:53
@gavazquez for sure. Also I've tested this latest nightly with my friend and we still appear 20km underground for each other, the nightly does not fix the issue. Right now, I am trying some other things to see if I can resolve this

**Comment by CorvetteCole** [comment] 2018-05-03 23:16
Update to anyone following: This bug occurs when one of the players has "Set time automatically" disabled in Windows settings. We solved this issue by installing NeTime and syncing our time with NTP servers. Turning "Set time automatically" on in Windows settings should theoretically fix this as well but was not tested.

**Comment by gavazquez** [comment] 2018-05-28 19:39
Fixed in nightly

**Closed by gavazquez** 2018-05-28 19:39 UTC
