### ISSUE TITLE
Subspace.txt error - more than one line

### ISSUE THREAD

**Issue by FlightMS** [LunaMultiplayer/LunaMultiplayer#417] opened 2021-04-12 23:27 UTC
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.11.2

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.27.0

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: NONE

------------------------------------------------------------------------------

Expected behaviour: No error message

------------------------------------------------------------------------------

Current behaviour: Error message about subspace error appears even when the subspace contains only one line

![LMPSubspaceError](https://user-images.githubusercontent.com/82420268/114474720-2252a100-9bf7-11eb-8c19-7a6fa5bd9c0e.PNG)
[Subspace.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/6300308/Subspace.txt)
[lmpserver_2021-04-13_01-23-24.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/6300312/lmpserver_2021-04-13_01-23-24.log)

------------------------------------------------------------------------------

Steps to reproduce: Start server and check logs

**Comment by Neshura87** [comment] 2021-05-02 01:51
Same issue, I wanna add to that: I am experiencing SEVERE FPS drops due to this, After switching the menu my FPS go up to where they should be and over the course of a few minutes drop down to 3.

Happens on all vanilla setup as well as modded so it is not caused by some mod conflict. Deleting Subspace.txt is the only workaround i've found.

In addition to that the Subspace.txt throws this error the moment it is saved, whether by the server or a text editor and independent of what was changed, reverting any changes does not fix the issues and as such it would seem the fact that the file was saved causes it to become corrupt.

**Comment by gavazquez** [comment] 2021-06-25 10:45
Fixed in nightly

**Closed by gavazquez** 2021-06-25 10:45 UTC
