### ISSUE TITLE
Randomly being disconnected from server. LmpCommon.Message.Data.Vessel.VesselProtoMsgData

### ISSUE THREAD

**Issue by Lopezak** [LunaMultiplayer/LunaMultiplayer#224] opened 2018-10-14 23:00 UTC
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

--- KSP Log ---
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2476944/KSP.log)

--- requested output log ---
[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2476945/output_log.txt)

--- server log ---
[lmpserver_2018-10-13_18-32-17.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2476946/lmpserver_2018-10-13_18-32-17.log)

--- server universe and config files --- 
[uni and config.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2476947/uni.and.config.zip)

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows 10

------------------------------------------------------------------------------

KSPVersion: 1.4.5.2243

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 
0.14.51

------------------------------------------------------------------------------

MODS (add link to download them): None (besides LMP of course)

------------------------------------------------------------------------------

Expected behaviour: Not to be randomly disconnected

------------------------------------------------------------------------------

Current behaviour: Randomly disconnecting. Seems to occur upon launching a craft from any one player. Other people are reporting possibly during scene changes <- Unconfirmed. 
This error was showing from the server console when disconnects occurred:
Client ShortguyGMR disconnected in Send network message error: , Endpoint 99.127.189.251:55650, error: Error serializing message! MsgDataType: LmpCommon.Message.Data.Vessel.VesselProtoMsgData Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CachedQuickLz.CachedQlz.Compress(Byte[]& data, Int32& length, Int32 level)
   at LmpCommon.Message.Data.Vessel.VesselProtoMsgData.InternalSerialize(NetOutgoingMessage lidgrenMsg) in C:\projects\lunamultiplayer\LmpCommon\Message\Data\Vessel\VesselProtoMsgData.cs:line 22
   at LmpCommon.Message.Base.MessageData.Serialize(NetOutgoingMessage lidgrenMsg) in C:\projects\lunamultiplayer\LmpCommon\Message\Base\MessageData.cs:line 42
   at LmpCommon.Message.Base.MessageBase`1.Serialize(NetOutgoingMessage lidgrenMsg) in C:\projects\lunamultiplayer\LmpCommon\Message\Base\MessageBase.cs:line 112

------------------------------------------------------------------------------

Steps to reproduce: We seemed to be able to reproduce by simply playing for a few minutes (usually about 5-10 minutes). I would typically be knocked out of the server when someone was launching a craft while I was on the KSC scene.

**Comment by mphelan6** [comment] 2018-10-16 04:13
I also am having this issue. I'm running the server on Ubuntu 18.04, LMP 0.14.51, KSP 1.5. I also had this issue on KSP 1.45 and LMP 0.13.50. We solved the problem by downgrading to LMP 0.12.49.



server log-
[lmpserver_2018-10-16_02-33-58.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2481384/lmpserver_2018-10-16_02-33-58.log)

**Comment by jan-vdm** [comment] 2018-10-16 12:52
Same issue, can't get all the info but, 

We are running Science mode on hard. Seems to be only happening alot when more thna 2 players are online at a time.

```
[12:43:51][Debug] : Hades acquired lock UnloadedUpdate - 40277816-c4b2-4c69-b0bb-dc16257d7b69
[12:43:51][Debug] : Hades acquired lock UnloadedUpdate - f5f6088b-0b20-4e99-9333-96830390edf3
[12:43:51][Debug] : Saving vessel 2edf64e2-990e-4986-ab5a-058f8f1772ad (45.9609375 KB) from Hades.
[12:43:51][Info] : Client legzs11 disconnected in Send network message error: , Endpoint (redacted ip):60265, error: Error serializing message! MsgDataType: LmpCommon.Message.Data.Vessel.VesselProtoMsgData Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at CachedQuickLz.CachedQlz.Compress (System.Byte[]& data, System.Int32& length, System.Int32 level) [0x00485] in <8bfaa73571c14b3d9984b32141bf7ea0>:0
  at LmpCommon.Message.Data.Vessel.VesselProtoMsgData.InternalSerialize (Lidgren.Network.NetOutgoingMessage lidgrenMsg) [0x00007] in <7b222fe8e04048a395f7738f408c50a1>:0
  at LmpCommon.Message.Base.MessageData.Serialize (Lidgren.Network.NetOutgoingMessage lidgrenMsg) [0x00036] in <7b222fe8e04048a395f7738f408c50a1>:0
  at LmpCommon.Message.Base.MessageBase`1[T].Serialize (Lidgren.Network.NetOutgoingMessage lidgrenMsg) [0x00029] in <7b222fe8e04048a395f7738f408c50a1>:0
[12:43:51][Debug] : Online Players: 1, connected: 2
[12:43:53][Info] : Client ShockingCactus (f6988f313a676f6a1cdf9b3dcf90804f369d192b) handshake successfully, Version: 0.13.50
[12:43:53][Debug] : Online Players: 2, connected: 2
```

**Comment by thygrrr** [comment] 2018-10-16 13:03
Thanks for the report, I don't precisely what is the cause but I can try to investigate.

If you have a savegame/universe that reproduces this problem reliably, Dagger and I would greatly appreciate it. We've been eyeing these sporadic (?) compression failures for some time now.

**Comment by jan-vdm** [comment] 2018-10-16 13:17
@thygrrr I'll get you the universe file tomorrow once my mate who's hosting wakes up. (he got the server up and running tonight I don't have rdp privileges yet)

But it seems to be in my case when the third connects sometimes, also when someone launches something. Usually the person doing something that's kicked, for example flying... pressing buttons in R&D but not yet whilst building. Also sometimes it can be the one connecting that's kicked straight away with that being produced on the console.

Also we have Universal plug and play disabled and also we don't connect to the master server. 

Hope this is enough to go on for now.

**Comment by thygrrr** [comment] 2018-10-16 13:17
Yeah, reading the log, it shows that whoever is SENDING the protovessel crashes. Thanks for clarifying!

**Comment by thygrrr** [comment] 2018-10-16 13:27
If we happen to be online at the same time, if it's ok with you I'd like to join the server with the client debugger running to see if I can catch the problem.

**Comment by thygrrr** [comment] 2018-10-16 13:29
Since this is a protovessel serialization problem, I wonder if it's related to which parts were built into the craft.

**Comment by jan-vdm** [comment] 2018-10-16 13:35
I'm on the discord as Shocking Cactus so feel free to ping me whenever I'm online the ksp server runs 24/7

**Comment by thygrrr** [comment] 2018-10-16 13:39
WHOA!!!

The bug report says this is 

> LMP version (include the build number if you are using a nighly build): 0.14.51

But this is actually a 0.13.50 server.

**Comment by Lopezak** [comment] 2018-10-16 23:08
@thygrrr That could possibly be cause we reverted to an older version to be able to play with a stable game. It doesn't seem to occur in 0.13.50, however, I can assure you that in the nightly I listed it was occurring regularly as well as in the current release. If you look at the server log I attached, the very first line shows that it is in 14.50 and the error occurs some time later in that log.

**Comment by gavazquez** [comment] 2018-10-19 15:00
ok fixed with commit: https://github.com/LunaMultiplayer/LunaMultiplayer/commit/6b9db3b27a108a823ba6b64b2a70f8596e7b8a38

Let me know if it works now with the latest nightly build

**Comment by gavazquez** [comment] 2018-10-19 21:28
Fixed as it was caused by the compressing race condition

**Closed by gavazquez** 2018-10-19 21:28 UTC
Labels: needs testing
