### ISSUE TITLE
Cant see player.

### ISSUE THREAD

**Issue by TheMidnightCrow** [LunaMultiplayer/LunaMultiplayer#137] opened 2018-05-15 00:12 UTC
https://www.dropbox.com/s/7bwrb9qjfe77gvm/Config.zip?dl=0
https://www.dropbox.com/s/1jf4tlib2n6b2sx/KSP.log?dl=0
https://www.dropbox.com/s/4609yoq74kkljut/LMPModControl.xml?dl=0
https://www.dropbox.com/s/xhu1k08191b8jwg/output_log.txt?dl=0
https://www.dropbox.com/s/kagi26yqjas1g9t/Universe.zip?dl=0

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: WIN 10

------------------------------------------------------------------------------

KSPVersion: 1.4.3

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.8.42

------------------------------------------------------------------------------

MODS (add link to download them): CKAN and simple construction

------------------------------------------------------------------------------

Expected behaviour: To see and interact with everyone.
------------------------------------------------------------------------------

Current behaviour: Their are 3 of us and we cant see the other guy but he can see us and if he leaves the game and comes back his ships are gone, how ever he still uses our money ans since and if he unlocks a node it unlocks for us.

------------------------------------------------------------------------------

Steps to reproduce: just log in to the server.

**Comment by gavazquez** [comment] 2018-05-21 10:07
Probably a subspace issue. Couldn't reproduce the bug so closing it

**Closed by gavazquez** 2018-05-21 10:07 UTC

**Comment by TheMidnightCrow** [comment] 2018-05-21 10:08
I kinda thought that to but it happens as soon as the server starts. He has
shit internet could that be it?

**Comment by gavazquez** [comment] 2018-05-21 10:10
Probably that's not helpful. Vessels are sent to each player and they might take a while to be sent if the server/client has a bad internet connection and the vessels are huge

**Comment by gavazquez** [comment] 2018-05-21 10:11
A method to compress the vessels and send them compressed is in the todo list but for now it's still not possible

**Comment by TheMidnightCrow** [comment] 2018-05-21 10:11
Right on well thanks for the help.
