### ISSUE TITLE
No saving of achieved science projects

### ISSUE THREAD

**Issue by S4ftl4den** [LunaMultiplayer/LunaMultiplayer#134] opened 2018-05-05 20:17 UTC
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1977035/KSP.log)

[output_log.txt](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1977038/output_log.txt)

[lmpserver 2018-05-05 15-07-11.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1977040/lmpserver.2018-05-05.15-07-11.log)

[LMPServer.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/1977047/LMPServer.zip)

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Win10

------------------------------------------------------------------------------

KSPVersion: 1.4.3

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.84.2

------------------------------------------------------------------------------

MODS (add link to download them): none

------------------------------------------------------------------------------

Expected behaviour: Saving of the achieved research projects.

------------------------------------------------------------------------------

Current behaviour: There is this area called archives or something, wich is currently showing nothing on the server. This makes it possible to research everything as many times as you desire. (Server Mode is Science)

------------------------------------------------------------------------------

Steps to reproduce: I do not know but currently the server is showing this buggy behaviour. I could always just start the server and let you on if that helps.

**Comment by gavazquez** [comment] 2018-05-06 09:34
Hi.

@MalteJanz  I think that the problem is that this part is not being correctly saved in the ResearchAndDevelopment.xml scenario file:

![image](https://user-images.githubusercontent.com/12727761/39671904-5d20bf0c-5121-11e8-86a6-d8c4fc19a09f.png)

I'll have a look and I'll try to solve it next week

**Comment by gavazquez** [comment] 2018-05-06 09:45
Also I atach the relevant events:

OnExperimentStored
OnExperimentDeployed
OnTriggeredDataTransmission

**Comment by S4ftl4den** [comment] 2018-05-22 15:31
Are you gonna get to work on this any time soon? Me and my friends would love to play.

**Comment by gavazquez** [comment] 2018-05-22 15:44
Not sure, got a lot of work at the office so this might be paused for a while. Anyway feel free to do a push request if u know coding

**Comment by gavazquez** [comment] 2018-05-28 10:45
Fixed in commit: https://github.com/LunaMultiplayer/LunaMultiplayer/commit/f04454dc3974aec621905c0b8322ad19ae935065

Only available in nightly version tough

**Closed by gavazquez** 2018-05-28 10:45 UTC
Labels: bug, help wanted

**Comment by S4ftl4den** [comment] 2018-05-31 17:10
Thank you so much!

**Comment by lnmds** [comment] 2018-08-13 07:40
Keep in mind this breaks compatibility with KSP versions pre-1.4.3 (haven't tested on 1.4.2, but 1.4.1 definitely breaks since it couldn't find the respective events).

It would be nice to have an update on `LMPGlobal/KSPCompatible.cs` to reflect the changes.

**Comment by gavazquez** [comment] 2018-08-13 07:44
I agree. Done and updated it to 1.4.3
