### ISSUE TITLE
Blank Window Glitch

### ISSUE THREAD

**Issue by CorruptKode** [LunaMultiplayer/LunaMultiplayer#147] opened 2018-06-04 06:02 UTC
If you click the Blue tower icon (server search) in the main menu before you click the gears (settings), the Settings window will be blank.

**Comment by gavazquez** [comment] 2018-06-04 07:11
Can't reproduce it:

![image](https://user-images.githubusercontent.com/12727761/40903285-2f1abb7c-67d7-11e8-8965-fb9c1c8e78f2.png)

Is there any extra step I must take?

**Comment by CorruptKode** [comment] 2018-06-04 07:20
Run KSP> Click Server Browser> Close Browser>Click Settings (sometimes click network settings) = Blank window.
![20180604031750_1](https://user-images.githubusercontent.com/39897591/40903678-32fa3730-67a6-11e8-8d4d-b59badbc92b4.jpg)

**Comment by gavazquez** [comment] 2018-06-04 07:27
Ok got it working :) Will be fixed on next release. Thanks!

**Closed** 2018-06-04 07:27 UTC
