### ISSUE TITLE
Latest LMP causes crash on startup

### ISSUE THREAD

**Issue by njbrown09** [LunaMultiplayer/LunaMultiplayer#178] opened 2018-08-22 21:22 UTC
Remember to attach the "KSP.log" and the "output_log.txt" whenever is possible!  
You can find the KSP.log in ".\Kerbal Space Program\KSP.log"  
And output_log.txt in "C:\Users\YOURUSERNAME\AppData\LocalLow\Squad\Kerbal Space Program\output_log.txt"
(you probably need to display hidden folders to get into AppData)

In case you are using a nighly build of LMP from appveyor include the build number.
For example: 0.0.9.**384**
Otherwise, specify the version of LMP you are using from the github releases.

**If you have access to the server. Please zip the whole "Universe" and "Config" folder.
Also if you are running mods in the server, attach the "LMPModControl.txt"**

------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Windows

------------------------------------------------------------------------------

KSPVersion: 1.4.5

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.11.47

------------------------------------------------------------------------------

MODS (add link to download them): Vanilla

------------------------------------------------------------------------------

Expected behaviour: The game boots

------------------------------------------------------------------------------

Current behaviour: The game gets an access violation

------------------------------------------------------------------------------

Steps to reproduce: Boot up LMP 0.11.47 in KSP 1.4.5

**Comment by gavazquez** [comment] 2018-08-22 22:09
Probably caused by mods. Also no log attached. Closing issue

**Closed by gavazquez** 2018-08-22 22:09 UTC

**Comment by njbrown09** [comment] 2018-08-25 20:59
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2321041/KSP.log)

**Comment by gavazquez** [comment] 2018-08-25 23:16
This is caused by remote tech mod as u can see in the ñast l'INE of t'he log. Will have a look once home but bear in mind that LMP does NOT support other mods
