### ISSUE TITLE
Vessel stops moving smoothly above 70km

### ISSUE THREAD

**Issue by Kruskovac** [LunaMultiplayer/LunaMultiplayer#273] opened 2019-01-30 17:32 UTC
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Client: Linux Mint 19/Windows 7
       Server: Raspbian Stretch Lite, Kernel 4.14

------------------------------------------------------------------------------

KSPVersion: 1.6.1

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): 0.20.2

------------------------------------------------------------------------------

MODS (add link to download them): None

------------------------------------------------------------------------------

Expected behaviour: Vessel should continue moving smoothly above 70km

------------------------------------------------------------------------------

Current behaviour: Above 70km the vessel stops moving and synchronizes every 1 to 3 seconds to the position it should be if it kept moving correctly. As soon as the vessel is below 70km the movement is smooth again. The server isn't showing any occurrences of CPU, RAM or VRAM limitations.

------------------------------------------------------------------------------

Steps to reproduce: Run LMP Server on RaspberryPi Model 3B+ and fly above 70km

[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2813723/KSP.log)
[lmpserver.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2813730/lmpserver.log)
[server_files.zip](https://github.com/LunaMultiplayer/LunaMultiplayer/files/2813732/server_files.zip)

**Comment by BrainP4in** [comment] 2019-02-03 11:03
We have the same problem on our Debian Linux Server, if you warp above 70km it works smoothly but in realtime it syncs every 1-3 seconds.

**Comment by bfalans** [comment] 2019-04-07 22:04
Same problem here on a windows 10 system. Looking into the mods that might cause it

**Comment by razaqq** [comment] 2020-06-05 12:30
same here, no mods installed

**Comment by Vluko** [comment] 2020-06-08 10:34
Map view seems to fix the problem until you exit it

**Comment by gavazquez** [comment] 2020-06-08 10:50
Can someone record a video or something about this so I can investigate? Do you mean that you must fly in formation with another vessel above 70km to see it but in map view it works?

Bear in mind guys that it takes a lot of time to fix a bug so if I don't reproduce it in a short amount of time because the bug report is not detailed enough I just skip it and close it

**Comment by Vluko** [comment] 2020-06-08 10:58
Every few seconds above 70k, the vessel snaps back to the position and location it was in about 3 seconds ago

**Comment by gavazquez** [comment] 2020-06-08 12:01
> 
> 
> Every few seconds above 70k, the vessel snaps back to the position and location it was in about 3 seconds ago

You mean in external view, in map view, what distance you are from the vessel that shows this behaviour?

**Comment by Chryseus** [comment] 2020-06-21 00:20
Same problem here, it's jumping forward in time by about 4 seconds, this occurs every 8 seconds or so when in orbit, the throttle setting goes to zero every time as well.
There appears to be some dependence on camera distance, it becomes less common when zoomed out fully, maybe every 15-20 seconds or sometimes stops entirely until you zoom back in, it does not happen in map view.
Dropping back in to the atmosphere also fixes the problem instantly.

**Comment by Sanfam** [comment] 2020-07-01 17:10
I'm running modded so I cannot contribute useful logs, but I've been attempting to debug this as well.  Once I exit an atmosphere, burns become difficult or impossible to reliably complete without constant mashing of max-throttle; The ship appears to be sync'd every few seconds back to a previous state where things like rotation state/inertia and throttle position/state are reset to a previous state.  Typically this results in a large craft in the process of turning simply halting every few degrees, and means burns hard-stop after a variable number of seconds.  I'm attempting to confirm an alternate scenario where the craft spontaneously restores a previous throttle state (Thus resuming a burn that was halted), but I wasn't paying enough attention at that time to confirm with absolute confidence.

I'll see what I can do to make this happen in a stock instance.

**Comment by TheRealOrange** [comment] 2020-07-10 13:47
I have the same issue. I have recorded an instance, but I have some mods installed including physics rang extender (which is disabled), ferram aerospace, kerbal engineer, and the docking alignment indicator. The LMPServer is running on Ubuntu 20.04, with mono version 6.10.0.104. The KSP version is 1.9.1.

This link is a video demonstrating the issue. It can be seen that the craft updates its position periodically, and all rotation is set to 0. This makes docking nearly impossible, as the craft docking port tends to clip into the other port instead when the position updates.
https://drive.google.com/file/d/1xVzVBcIALQOjA94yofdIMr5xbBTPKOyr/view?usp=sharing

**Comment by gavazquez** [comment] 2020-07-12 10:49
@TheRealOrange please attach the log and the universe of the server when that happens **so I have the same vessels to test**. It seems that the vessel is being removed and recreated again but I don't feel like trying a lot of combinations of different vessels until I catch it.

**Closed** 2020-07-12 13:57 UTC

**Comment by gavazquez** [comment] 2020-07-12 13:59
So this happened because for some users with american regional settings the StartTime.txt file on the server was being generated with american date format:

![image](https://user-images.githubusercontent.com/12727761/87248204-7a862800-c458-11ea-913c-0e22a2e3a693.png)

I use Spanish format of DD/MM/YYYY and never looked into this so LMP server understood that the date today was in the future and the time sync became a mess...

It should be fixed now as I use standard ISO 8601 format
