### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by llacqie** [LunaMultiplayer/LunaMultiplayer#416] opened 2021-04-02 07:32 UTC
------------------------------------------------------------------------------
------------------------------------------------------------------------------
------------------------------------------------------------------------------

OS: Ubuntu 20.04

------------------------------------------------------------------------------

KSPVersion: Latest release

------------------------------------------------------------------------------

LMP version (include the build number if you are using a nighly build): Latest release

------------------------------------------------------------------------------

MODS. Remember that **mods are not supported**: NO MODS

------------------------------------------------------------------------------

![изображение](https://user-images.githubusercontent.com/46074473/113392661-e6c20680-93ae-11eb-940d-ab29053f148c.png)
![изображение](https://user-images.githubusercontent.com/46074473/113392670-ea558d80-93ae-11eb-9373-dde6d1aa3549.png)

https://www.youtube.com/watch?v=IiKqqUU8a2g

Errors are displayed continuously, the longer you are on the server, the more it slows down

------------------------------------------------------------------------------

**Comment by x3lebr4e** [comment] 2021-04-02 07:36
https://www.youtube.com/watch?v=IiKqqUU8a2g

**Comment by x3lebr4e** [comment] 2021-04-02 08:00
upd: This can be fixed by deleting all the crafts through the SERVER console, but after some time (when the players create more crafts and do something with them) the bug will repeat itself.

**Comment by x3lebr4e** [comment] 2021-04-02 08:06
I think that the bug is caused by a craft that is not destroyed correctly. (It was destroyed in the game, but the server still thinks that it is not destroyed)

**Comment by x3lebr4e** [comment] 2021-04-02 08:23
[KSP.log](https://github.com/LunaMultiplayer/LunaMultiplayer/files/6248521/KSP.log)

**Comment by gavazquez** [comment] 2021-07-02 10:03
You have a problem with this vessel:

`e98c4f09-46dc-475b-b37a-ecdc9f71c7a4`
![image](https://user-images.githubusercontent.com/12727761/124258037-41ddd380-db2d-11eb-9524-8a79bfdddcdc.png)

Somehow, somebody screwed the flag parts in the vessel so they look like:

```
MESH
{
	name = medium
	displayName = Средний
	meshName = 2.5MediumPortrait
	orientation = PORTRAIT
}
```

And they should be:

```
MESH
{
	name = medium
	displayName = Средний
	meshName = 2.5MediumLandscape
	orientation = LANDSCAPE
	mass = 0.000675000018
	cost = 12.5
	variantNames = White,Dark,Orange,TransparentBackground
	indexOffset = 0
}
```

**Comment by llacqie** [comment] 2021-07-02 10:15
And how to avoid this?

**Comment by gavazquez** [comment] 2021-07-02 10:16
No idea, probably a user had a mod or something like that since he screwed up part data

**Closed** 2021-07-02 10:17 UTC

**Comment by llacqie** [comment] 2021-07-02 10:24
That is, as a result, any person can break any server?

**Comment by gavazquez** [comment] 2021-07-02 10:57
Using corrupted vessels? yes, probably. LMP does not support mods

**Comment by llacqie** [comment] 2021-07-02 12:14
Can I forbid the use of any parts other than stock ones?

**Comment by gavazquez** [comment] 2021-07-02 12:32
Yes https://github.com/LunaMultiplayer/LunaMultiplayer/wiki/Mod-file
